steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args:
      - "build"
      - "-t"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/factorybrain-edge/factorybrain-edge-backend:$COMMIT_SHA"
      - "-f"
      - "Dockerfile"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/factorybrain-edge/factorybrain-edge-backend:$COMMIT_SHA"

images:
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/factorybrain-edge/factorybrain-edge-backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY